### ISSUE TITLE
EWSPoster crashes with Tanner

### ISSUE THREAD

**Issue by t3chn0m4g3** [telekom-security/ewsposter#1]
Some conditions lead to crashing ewsposter:
```
 => Starting Tanner Modul.
 => Send Limit is set to : 500. Adapting to limit!
Traceback (most recent call last):
  File "/opt/ewsposter/ews.py", line 2610, in <module>
    eval(i+'()')
  File "<string>", line 1, in <module>
  File "/opt/ewsposter/ews.py", line 2436, in tanner
    REQUEST["raw"] = base64.b64encode(reassembledReq.encode('ascii')).decode()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 459-462: ordinal not in range(128)
```
I sent you the logs via eMail.

**Comment by t3chn0m4g3** [comment]
@trixam Thanks. New images are building, will track and then close.
